# yaml-language-server: $schema=https://topaz.sh/schema/config.json
---
# config schema version
version: 2

logging:
  prod: true
  log_level: info

# directory:
  # db_path: '${TOPAZ_DB_DIR}/az1.db'
  # request_timeout: 5s # set as default, 5 secs.

# remote directory is used to resolve the identity for the authorizer.
remote_directory:
  address: topaz-ds:9292 # set as default, it should be the same as the reader as we resolve the identity from the local directory service.
  insecure: true

# default jwt validation configuration
jwt:
  acceptable_time_skew_seconds: 5 # set as default, 5 secs

api:
  health:
    listen_address: "0.0.0.0:9494"

  metrics:
    listen_address: "0.0.0.0:9696"

  services:
    # console:
    #   grpc:
    #     listen_address: "0.0.0.0:9292"
    #     fqdn: ""
    #     certs:
    #       tls_key_path: '${TOPAZ_CERTS_DIR}/grpc.key'
    #       tls_cert_path: '${TOPAZ_CERTS_DIR}/grpc.crt'
    #       tls_ca_cert_path: '${TOPAZ_CERTS_DIR}/grpc-ca.crt'
    #   gateway:
    #     listen_address: "0.0.0.0:9393"
    #     fqdn: "https://localhost:29393"
    #     allowed_headers:
    #     - "Authorization"
    #     - "Content-Type"
    #     - "If-Match"
    #     - "If-None-Match"
    #     - "Depth"
    #     allowed_methods:
    #     - "GET"
    #     - "POST"
    #     - "HEAD"
    #     - "DELETE"
    #     - "PUT"
    #     - "PATCH"
    #     - "PROFIND"
    #     - "MKCOL"
    #     - "COPY"
    #     - "MOVE"
    #     allowed_origins:
    #     - http://localhost
    #     - http://localhost:*
    #     - https://localhost
    #     - https://localhost:*
    #     - https://0.0.0.0:*
    #     - https://*.aserto.com
    #     - https://*aserto-console.netlify.app
    #     certs:
    #       tls_key_path: '${TOPAZ_CERTS_DIR}/gateway.key'
    #       tls_cert_path: '${TOPAZ_CERTS_DIR}/gateway.crt'
    #       tls_ca_cert_path: '${TOPAZ_CERTS_DIR}/gateway-ca.crt'
    #     http: false
    #     read_timeout: 2s
    #     read_header_timeout: 2s
    #     write_timeout: 2s
    #     idle_timeout: 30s

    authorizer:
      grpc:
        listen_address: "0.0.0.0:9292"
        fqdn: ""
        certs:
          tls_key_path: '${TOPAZ_CERTS_DIR}/grpc.key'
          tls_cert_path: '${TOPAZ_CERTS_DIR}/grpc.crt'
          tls_ca_cert_path: '${TOPAZ_CERTS_DIR}/grpc-ca.crt'
      gateway:
        listen_address: "0.0.0.0:9393"
        fqdn: "https://localhost:29393"
        certs:
          tls_key_path: '${TOPAZ_CERTS_DIR}/gateway.key'
          tls_cert_path: '${TOPAZ_CERTS_DIR}/gateway.crt'
          tls_ca_cert_path: '${TOPAZ_CERTS_DIR}/gateway-ca.crt'
        allowed_origins:
        - http://localhost
        - http://localhost:*
        - https://localhost
        - https://localhost:*
        - https://0.0.0.0:*
        - https://*.aserto.com
        - https://*aserto-console.netlify.app
        allowed_headers:
        - "Authorization"
        - "Content-Type"
        - "If-Match"
        - "If-None-Match"
        - "Depth"
        allowed_methods:
        - "GET"
        - "POST"
        - "HEAD"
        - "DELETE"
        - "PUT"
        - "PATCH"
        - "PROFIND"
        - "MKCOL"
        - "COPY"
        - "MOVE"
        http: false
        read_timeout: 2s
        read_header_timeout: 2s
        write_timeout: 2s
        idle_timeout: 30s

opa:
  instance_id: "-"
  graceful_shutdown_period_seconds: 2
  # max_plugin_wait_time_seconds: 30 set as default
  local_bundles:
    paths: []
    skip_verification: true
  config:
    services:
      ghcr:
        url: https://ghcr.io
        type: "oci"
        response_header_timeout_seconds: 5
    bundles:
      test:
        service: ghcr
        resource: "ghcr.io/aserto-policies/policy-rebac:latest"
        persist: false
        config:
          polling:
            min_delay_seconds: 60
            max_delay_seconds: 120
